### ISSUE TITLE
Bug: background resolution

### ISSUE THREAD

**Issue by SmilleyMLK** [UltraStar-Deluxe/DevOps#32]
I haven't seen it with other users, and it may have to do with my graphics card, but everytime I use a background image with a resolution larger than ~ 1024x1024 pix, I get a greyscale jumbled image, like this: http://www.imagebam.com/image/f1a612440765968
The original, by comparison, looks like this: http://www.imagebam.com/image/85ddb4440766375

**Comment by basisbit** [comment]
does this still happen with the current USDX v1.2 alpha from 3 days ago?
http://derpy.ws/builds/windows/trunk/latest/latest.7z

**Comment by SmilleyMLK** [comment]
Looks even worse now, actually. Just random static. And I can't do screenshots. At under 1000x1000, it still displays correctly.

**Comment by basisbit** [comment]
tried to reproduce the issue but without success. What graphics card do you have and also please provide the error.log file

**Comment by SmilleyMLK** [comment]
I've got an ATI Radeon X1600, one of the last video cards that used the AGP-port. 
It never 100% agreed with the rest of my hardware, though. The artwork at the PC's startup are screwed up beyond recognition. But everything else works fine.
As for the error.log, it's not particularly enlightening: http://sta.sh/01qkj7ctylna

**Comment by basisbit** [comment]
error log contained everything I needed: "OpenGL TextureNPOT-support: -1" This says that the graphics card says it support NPOT.
Google came up with this: "Old ATI driver versions (particulary those for older hardware such as X1600 which are not updated anymore) have bugs in NPOT implementation so even though they claim it is supported it usually doesn't work properly and produces garbled textures."
I will implement a check for "Radeon X1600/X1650 Series" so that advanced image manipulation won't be done on this graphics card but instead on the CPU (just like the old USDX versions did before).

**Comment by basisbit** [comment]
could you please test with this version again: https://derpy.ws/builds/windows/trunk/latest/latest.7z

**Comment by SmilleyMLK** [comment]
Now it's back to the old, grayscale background. Here's the new error.log: http://sta.sh/0xoj2q0xql

**Comment by basisbit** [comment]
this is a graphics-card opengl bug. will close this for now.
